export type ArtworkStatus = 'Available' | 'Sold' | 'Reserved';

export interface Artwork {
    id: string;
    customId: string; // User defined ID
    title: string;
    artist?: string;
    artworkYear?: string;
    descriptionTitle?: string;
    description: string;
    dimensions: string;
    medium: string;
    status: ArtworkStatus;
    location: string;
    price: number;
    plusGst?: boolean;
    imageUrls: string[]; // Changed from imageUrl to imageUrls array
    createdAt: number;
}

export interface Collection {
    id: string;
    name: string;
    description: string;
    artworkIds: string[];
    coverImageUrl?: string;
    createdAt?: number;
}

export interface Catalog {
    id: string;
    name: string;
    description: string;
    artworkIds: string[];
    coverImageUrl: string;
    createdAt: number;
    /** Stored PDF (in R2) — either generated by the studio or uploaded. */
    pdfUrl?: string;
    /** How this catalog came to be; defaults to 'generated' for older rows. */
    source?: 'generated' | 'uploaded';
}

export type LogoPlacement =
    | 'Top Left' | 'Top Center' | 'Top Right'
    | 'Bottom Left' | 'Bottom Center' | 'Bottom Right';

export interface PdfOptions {
    showCatalogName: boolean;
    showTitle: boolean;
    showTitleNote: boolean;
    showDimensions: boolean;
    showPrice: boolean;
    showDescription: boolean;
    logoSelection: 'Select 1' | 'Select 2';
    logoPlacement: LogoPlacement;
    /** Nudge from the placement, in millimetres (+ = right / down). */
    logoOffsetX?: number;
    logoOffsetY?: number;
    /** Logo size: its longer side, in millimetres (default 32.4). */
    logoSize?: number;
    pageOptions: string[];
    customLogo1?: string;
    customLogo2?: string;
    /** Up to five reusable end-page designs (uploaded image URLs). */
    endPageDesigns?: string[];
    /** The design appended once after every other page; unset = no last page. */
    lastPage?: string;
    removeBackground?: boolean;
    imageShadow?: boolean;
    /** 'Default' (follow theme), a hex color like '#0f172a', or a legacy named palette. */
    colorPalette?: string;
    /** The main colour whose shades the studio shows ('blue', 'grey' …). */
    colorFamily?: string;
    /** Retired (hue wheel + depth slider); read by nothing, kept so old saves load. */
    colorHue?: number;
    colorIntensity?: number;
    /** Up to 6 most recently used page colors. */
    recentColors?: string[];
    gradientStyle?: 'Solid' | 'Linear' | 'Radial' | 'Diagonal' | 'Vignette' | 'Spotlight';
}

export type CatalogTheme = 1 | 2 | 3 | 4 | 5;

export interface InvoiceItem {
    artworkId: string;
    title: string;
    price: number;
}

/** A proforma invoice (quotation). Synced through the server; a copy is kept on each device for offline use. */
export interface Invoice {
    id: string;
    invoiceNumber: string;
    customerName: string;
    customerEmail: string;
    customerPhone?: string;
    customerAddress?: string;
    /** Set when the proforma was generated from an inquiry. */
    inquiryId?: string;
    items: InvoiceItem[];
    subtotal: number;
    taxRate: number;
    total: number;
    date: number;
    status: 'Draft' | 'Sent' | 'Paid';
}

export interface Inquiry {
    id: string;
    inquiryNumber: string;
    customerName: string;
    customerPhone: string;
    customerEmail: string;
    customerAddress?: string;
    artworkIds: string[];
    notes: string;
    /** 'Private room': sent by a client from a private viewing room. */
    source: 'Walk-in' | 'Phone' | 'Email' | 'Social Media' | 'Referral' | 'Private room' | 'Other';
    status: 'New' | 'Contacted' | 'Interested' | 'Converted' | 'Closed';
    catalogShared: boolean;
    date: number;
    /** Set by the server from the creating user's session. */
    createdBy?: string;
    createdByName?: string;
    /** Photos taken or picked for this inquiry (R2 URLs). */
    imageUrls?: string[];
}

export interface EventTodo {
    id: string;
    text: string;
    /** Assigned team member; optional. */
    assigneeId?: string;
    assigneeName?: string;
    done: boolean;
    createdAt: number;
}

export interface CalendarEvent {
    id: string;
    title: string;
    /** Epoch ms when the event starts. */
    date: number;
    /** Optional end — for multi-day events (e.g. an exhibition running all month). */
    endDate?: number;
    notes?: string;
    /** Hex color identifying this event on the calendar (distinct from holidays). */
    color?: string;
    /** Event-planner task list with assignees. */
    todos: EventTodo[];
    createdAt: number;
    createdBy?: string;
    createdByName?: string;
}

/** An archived record in the admin "Deleted" section. */
export interface DeletedItem {
    id: string;
    entity: string;
    entityId: string;
    summary: string;
    payload?: unknown;
    deletedAt: number;
    deletedBy?: string;
    deletedByName?: string;
}

export interface UserProfile {
    id: string;
    name: string;
    email: string;
    phone: string;
    address: string;
    password?: string; // Added for local auth simulation
    theme?: 'light' | 'dark';
    isOnline?: boolean;
}

export type MessageTag = 'General' | 'Urgent' | 'Follow-up' | 'Artwork' | 'Inquiry' | 'Invoice';

/** 'failed' is client-only: the server never accepted the message. */
export type MessageStatus = 'sent' | 'delivered' | 'read' | 'failed';

export interface MessageReplyTo {
    id: string;
    senderName: string;
    text: string;
}

export interface MessageAttachment {
    type: 'image' | 'file';
    url: string; // data URL
    name: string;
}

export interface Message {
    id: string;
    conversationId: string;
    senderId: string;
    senderName: string;
    text: string;
    tags: MessageTag[];
    timestamp: number;
    status?: MessageStatus;
    replyTo?: MessageReplyTo;
    attachment?: MessageAttachment;
}

export interface Conversation {
    id: string;
    participantIds: string[];
    participantNames: string[];
    lastMessage: string;
    lastMessageTime: number;
    unreadCount: number;
    title?: string;
    reason?: string;
    note?: string;
    isGroup?: boolean;
    groupName?: string;
    isPinned?: boolean;
    isArchived?: boolean;
    /** A private room: a closed group only its members can see (privateRooms.ts). */
    isPrivate?: boolean;
    /** Who created it; for a private room, its manager. Set by the server. */
    createdBy?: string;
}

export interface ConversationDetails {
    title?: string;
    reason?: string;
    note?: string;
}

export interface InquiryMessage {
    id: string;
    inquiryId: string;
    senderId: string;
    senderName: string;
    text: string;
    tags: MessageTag[];
    timestamp: number;
    status?: MessageStatus;
    replyTo?: MessageReplyTo;
    attachment?: MessageAttachment;
}

export interface Contact {
    id: string;
    name: string;
    phone: string;
    email?: string;
    notes?: string;
    /** 'inquiry' entries are derived client-side from inquiries and not stored in D1. */
    source: 'manual' | 'import' | 'inquiry';
    createdAt: number;
    createdBy?: string;
    createdByName?: string;
}

/** A store geofence configuration for employee attendance. */
export interface StoreConfig {
    id: string;
    name: string;
    latitude: number;
    longitude: number;
    /** Geofence radius in meters. */
    gpsRadius: number;
    /** Require Store Wi-Fi ON/OFF — server-side toggle, core flow unchanged. */
    wifiRequired: boolean;
    /** Approved Wi-Fi network name (SSID). */
    wifiSsid: string;
    createdAt: number;
}

/** One attendance record. ALL timestamps are server-generated. */
export interface AttendanceRecord {
    id: string;
    employeeId: string;
    employeeName: string;
    storeId: string;
    checkInAt: number | null;
    checkInLat: number | null;
    checkInLng: number | null;
    checkInAccuracy: number | null;
    checkOutAt: number | null;
    checkOutLat: number | null;
    checkOutLng: number | null;
    checkOutAccuracy: number | null;
    /** 'wifi' | 'mobile' | 'unknown' — as reported by the device. */
    connectionType: string;
    /** 'checked-in' | 'checked-out'. */
    status: string;
    createdAt: number;
}

/** A contact as passed by the UI before id/creator metadata is stamped. */
export type NewContact = Omit<Contact, 'id' | 'createdAt' | 'createdBy' | 'createdByName'>;

export type ViewState = 'login' | 'home' | 'artworks' | 'collections' | 'catalogs' | 'contacts' | 'calendar' | 'attendance' | 'invoice' | 'inquiry' | 'messaging' | 'profile' | 'activity' | 'payments';

export interface PaymentLink {
    id: string;
    shortUrl: string;
    amount: number; // paise
    description: string;
    customerName: string;
    customerPhone: string;
    customerEmail: string;
    /** Razorpay link status; unknown future statuses pass through as plain strings. */
    status: string;
    createdAt: number;
    createdBy: string;
    createdByName: string;
    paidAt?: number;
    paymentId?: string;
    paymentMethod?: string;
    /** When the link stops accepting payment; unset on older links (Razorpay's default). */
    expiresAt?: number;
}
